<?php

/**
 * @file
 * Enables Menugroup functionality.
 */

use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Drupal\group\Access\GroupAccessResult;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function menugroup_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $account = \Drupal::currentUser();
  $roles = [];
  $roles = $account->getRoles();

  if (isset($roles[1]) && $roles[1] != 'admin' && $roles[1] != "administrator") {
    if ($form_id == 'menu_edit_form') {
      $current_path = \Drupal::service('path.current')->getPath();
      $path_args = explode('/', $current_path);
      $row = \Drupal::database()
        ->query("SELECT count(*) as c, group_id FROM group_group_menu_menugroup WHERE menu_id='" . $path_args[5] . "' GROUP BY group_id")
        ->fetchObject();
      if ($row->c) {
        $group = entity_load('group', $row->id_group);
        $perm = 'Administer group menu';
        $result_object = GroupAccessResult::allowedIfHasGroupPermission($group, $account, $perm, 'AND');
        $tab = explode('\\', get_class($result_object));
        if ($tab[3] != 'AccessResultAllowed') {
          throw new AccessDeniedHttpException();
        }
      }
      else {
        $account = \Drupal::currentUser();
        $bool = $account->hasPermission('Access Menu information');
        if ($bool != '1') {
          throw new AccessDeniedHttpException();
        }
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function menugroup_theme() {
  return [
    'menu_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function menugroup_preprocess_page(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  if ($current_path == "/admin/structure/menu") {
    $account = \Drupal::currentUser();
    $roles = [];
    $roles = $account->getRoles();
    if (isset($roles[1]) && $roles[1] != 'admin' && $roles[1] != "administrator") {
      $bool = $account->hasPermission('Access Menu information');
      if ($bool != '1') {
        throw new AccessDeniedHttpException();
      }
    }
  }
}

/**
 * Implements hook_menu_delete().
 */
function menugroup_menu_delete($menu) {
  $menu_id = $menu->id();
  $delq = "Delete from group_group_menu_menugroup where menu_id = '$menu_id'";
  \Drupal::database()->query($delq);
}
